### ISSUE TITLE
How to access your API

### ISSUE THREAD

**Issue by sabbirsr** [islamic-network/alquran.cloud#10]
When I am trying to get data from your API your API response was blocked by CORS policy.
I think missing access key if yes please provide a link for getting access key or you can suggest me how do I use that

**Comment by meezaan** [comment]
Al Salaamu Alaykum.

Sorry I've just seen this. There are no API keys - it's like a problem on your local environment and the browser will be blocking the request.

Can you share your code and we can try and help.

**Comment by abdokhe** [comment]
A salamu Alaykum.

Here what I got if I try to fetch an image an audio in frontend using js.
this the code. You can Test It:
<h2>This code is just for consoling it out</h2>
<code>
fetch("http://cdn.alquran.cloud/media/image/2/255").then(res => {
  console.log(res);
}).catch(error => {
  console.error(error);
});
</code>
<h3> And this one for getting the image (blob) data</h3>
<code>
fetch("http://cdn.alquran.cloud/media/image/2/255").then(res => {
  res.blob();
}).then(blob => {
  // uncomment the code below to see the image data in the console
  // console.log(blob);
  return blob;
}).catch(error => {
  console.error(error);
});
</code>
