### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by WebPajooh** [islamic-network/alquran.cloud#11]
Hi bro.
How to get a translation and a text/voice version in one request?

http://api.alquran.cloud/v1/ayah/1:1/ar.muhammadayyoub
I get the text/voice of the ayah with this link, but It's doesnt have any translations.

I need to combine the previous request with this:
http://api.alquran.cloud/v1/ayah/1:1/fa.khorramdel

Help me please,
Thanks.

**Comment by meezaan** [comment]
Al Salaamu Alaykum.

Like this: http://api.alquran.cloud/v1/ayah/1/editions/ar.muhammadayyoub,fa.khorramdel
