### ISSUE TITLE
getting Audio File path with API

### ISSUE THREAD

**Issue by Mohsen322** [islamic-network/alquran.cloud#12]
hello
thanks for your great api
how can i get access to the direct path of every audio file in this api route?
http://api.alquran.cloud/v1/edition?format=audio&language=ar&type=versebyverse

i mean such a like this:
yoursite.com/albaqara.mp3

**Comment by meezaan** [comment]
You will have to loop over each edition, then call the quran or surah endpoint accordingly.

So, for instance: http://api.alquran.cloud/v1/surah/1/ar.abdullahbasfar
