### ISSUE TITLE
CDN sending null responses.

### ISSUE THREAD

**Issue by elboboua** [islamic-network/alquran.cloud#13]
Requests to the CDN to receive surah audio is not working with at least alafasy's audio files. Two days ago, it was working fine. 

example request: https://cdn.alquran.cloud/media/audio/ayah/ar.alafasy/1
response: not found

**Comment by meezaan** [comment]
I am able to see it. Where are you based? Is the response still a 200?

**Comment by elboboua** [comment]
Salam, brother. 

I am based in Lebanon. 

It seems like the issue has been resolved and my chrome browser has cached the null responses from yesterday. Did you notice it being down yesterday or was I just experiencing issues on my end?

**Comment by meezaan** [comment]
Alaykum Salaam.

I did not see any alerts come through. Cloudflare did not report any outages on any of their PoPs either, so it is strange that your browser somehow cached a null response.

I will have a look in the logs to see if something happened and will let you know if I find anything.

**Comment by elboboua** [comment]
So it seems that there is still an ongoing issue in my region at the least. Only certain ayat are playing when I use them as a url in the browser, but none are triggering onload events because the responses are coming back null. 

<img width="1115" alt="Screen Shot 2019-09-05 at 11 37 12 PM" src="https://user-images.githubusercontent.com/44094673/64378809-2fc8a200-d036-11e9-9792-36daf243f76e.png">
<img width="820" alt="Screen Shot 2019-09-05 at 11 36 53 PM" src="https://user-images.githubusercontent.com/44094673/64378811-30613880-d036-11e9-9078-4247413da50f.png">

**Comment by meezaan** [comment]
OK I've found the issue, I'm on it.

**Comment by meezaan** [comment]
So, the whole thing runs on a Docker Swarm between Digital Ocean and Linode with mounted volumes that are synchronised. On September 4, it appears that Digital Ocean restarted the VM (without telling us, they tend to do that - Linode is much better here) except this time they managed to bring it up with a volume with the files somehow being missing. That then synchronised with the Linode VM and deleted those files.

I've tried restoring from the backup at Digital Ocean spaces, but that times out to. So I'm now restoring from a backup from OneDrive. This will take time, so I appreciate your patience and thank you for reporting it.

I think it's also time to stop using Digital Ocean. We added them to the mix to diversity to the infrastructure, but they randomly restart machines and this has somehow been a result of that.

I'll keep you posted when the restore is done.

**Comment by meezaan** [comment]
The files have been restored now and I've flushed the cache at Cloudflare, so you should be able to get the files now after flushing your browser's cache.

Please let me know if you have any issues and thank you for bringing this to my attention.

**Comment by elboboua** [comment]
Much appreciated, Meezaan! Do you have a twitter I could follow to keep up with your work?

**Comment by meezaan** [comment]
Alhamdulillah. Sorry brother, I don't have a twitter account. Your thanks is enough. 

You can join the Islamic Network Discord group - I do try to mention changes / updates there - https://discord.gg/FwUy69M.
