### ISSUE TITLE
Showing Wrong Translation of Aya 8:64

### ISSUE THREAD

**Issue by rashnk** [islamic-network/alquran.cloud#16]
Assalamu alaikum,
There is an issue in the Malayalam translation https://alquran.cloud/ayah?reference=8%3A64, it is showing wrong aya meaning

Issue details
Translation  : "identifier":"ml.abdulhameed","language":"ml"
Sura : 8 Anfal
Aya : 64

It is showing translation of Sura 7: aya 64

for correct translation , please visit http://tanzil.net/#8:64  >  select Malayalam in Translation box , see the be image below
![image](https://user-images.githubusercontent.com/12730428/96348461-8d973c80-10c6-11eb-9999-e8eafaae07c2.png)

Quran cloud API screen shot below

![image](https://user-images.githubusercontent.com/12730428/96348477-a9024780-10c6-11eb-9774-d83de07af45f.png)

Please correct this ASAP, may I know how this kind of error occurs. how do we make sure that there is no more issue like this in the other sura translation?

**Comment by meezaan** [comment]
Alaykum Salaam.

Thank you for pointing this out. I will try and correct it today.

The issue is actually part of the source data that came from globalquran.com - it also exists on that website.

The source of the data is actually listed Tanzil.net, last updated at 2016-02-07.

**Comment by meezaan** [comment]
Updated.
