### ISSUE TITLE
Kitab Font: علامات الترقيم

### ISSUE THREAD

**Issue by rusdyahmad** [islamic-network/alquran.cloud#18]
How to fix punctuation in Kitab Font? Example for ayah 18:2

![ayah 18:2](https://i.imgur.com/ax76PGZ.png)

Correct version:

![ayah 18:2](https://i.imgur.com/Cl8tjbs.png)

**Comment by meezaan** [comment]
@rusdyahmad Al Salaamu Alaykum.

Both versions are valid in Classical Arabic- in fact, the way it appears with the Kitaab font is the way it appears in the majority of the fonts. Also, in different mushaf, you will it appear either way.

**Comment by rusdyahmad** [comment]
@meezaan Thanks bro.

I have changed using the [Isep Misbah](https://lajnah.kemenag.go.id/unduhan/category/1-qkiw) font.
