### ISSUE TITLE
The URL is not en.asad edition but the descriptions is

### ISSUE THREAD

**Issue by alfanzain** [islamic-network/alquran.cloud#21]
```
http://api.alquran.cloud/v1/ayah/262 - (Text) Returns Muhammad Asad's translation Ayat Al Kursi
http://api.alquran.cloud/v1/ayah/2:255 - (Text) Returns Muhammad Asad's translation Ayat Al Kursi
```

should be

`http://api.alquran.cloud/v1/ayah/262/en.asad - (Text) Returns Muhammad Asad's translation Ayat Al Kursi
http://api.alquran.cloud/v1/ayah/2:255/en.asad - (Text) Returns Muhammad Asad's translation Ayat Al Kursi`

**Comment by alfanzain** [comment]
Fixed by PR

**Comment by meezaan** [comment]
Fixed in https://github.com/islamic-network/alquran.cloud/issues/42.
