### ISSUE TITLE
GraphQL API

### ISSUE THREAD

**Issue by azzamsa** [islamic-network/alquran.cloud#31]
Hi.

Is there a plan to provide GraphQL API?
Thanks a lot for this awesome app.

**Comment by meezaan** [comment]
Al Salaamu Alaykum.

There is no such plan at this point - the resources aren't that complicated.

But if you feel like it's a necessity, we can look into it if you would like to contribute?

Alhamudlillah - all praise is due to Allah.

**Comment by azzamsa** [comment]
> But if you feel like it's a necessity, we can look into it if you would like to contribute?

Oh, I see. 
I don't have any experience with PHP :)
