### ISSUE TITLE
Tajweed Quraan in indopak font/text

### ISSUE THREAD

**Issue by ozayr** [islamic-network/alquran.cloud#33]
As Salaam u Alaykum,

Beloved brothers, Jazakallahu Khairan wa ahsanal jazaa, May Allah Suhanahu Wa Ta'ala reward you abundantly for this project.

I was wondering if its possible to get the tajweed Quraan in indopak text, I am attempting to make a tajweed parser that's decoupled from html eg, given the Ayah have a meta field attached that has the start and end indices of the tajweed rule, I have replicated the current parser from the brother that ported it to JS into python did some tweaks and can generate the required meta.

Initially I was then hoping this could be used in other languages or apps to then get the ayah and then highlight programmatically in a language agnostic way. This can be achieved with the meta but only for the same text type which is uthmaani.

Here in South Africa the most common text is most similar to the Quraan-simple-enhanced, I thought I maybe able to use the meta to highlight the tajweed rules taken from Quraan-tajweed, however there are differences that render the extracted indices unaligned. 

if there exists an indopak text decorated with the same tajweed tags as the tajweed-quraan I would be able to achieve what I'm trying to do, any advice or direction would be appreciated.

JazakAllah

**Comment by meezaan** [comment]
Alaykum Salaam brother,

Thank you for your prayers.

I am currently not aware on any IndoPak text existing in that format. If you have an IndoPak text one could look to port over the tajweed, but we would need someone to look through it and make sure it is correct. It would become a project on its own, I would think, but worth doing if we can possibly find some scholarly backing for a review of the rendered version.
