### ISSUE TITLE
net::ERR_INCOMPLETE_CHUNKED_ENCODING 200 (OK)

### ISSUE THREAD

**Issue by asadmalik** [islamic-network/alquran.cloud#34]
Assalam O Alikum

First of all thank you so much for the great service you are providing. May Allah provide the team with the best of rewards and then some. 

For last couple of days, I am getting "net::ERR_INCOMPLETE_CHUNKED_ENCODING 200 (OK)" error, when trying to access api with JavaScript fetch method. I am trying to fetch multiple translations within a loop and getting this error consistently on some of the translations as below:
- ru.porokhova ()
- ru.abuadel
- uz.sodik
- ur.modudi
 among others.

Please note I am not getting this on all the translations but only few mentioned above. I am only using JavaScript and have also tired with jQuery.getJSON() method as well with same result.
 
Am I missing some setting or precaution? Or do I need to use any other fetch method like jQuery AJAX or XMLHTTPRequest? 

Please let me know if you need more information or screenshots. Development is all local so I cannot share any URL for sample.

Thank you.

Screenshot:
![image](https://user-images.githubusercontent.com/3779182/227784242-41ea0935-a469-4868-9cd8-1b778793d116.png)

**Comment by meezaan** [comment]
Alaykum salaam brother.

This issue is almost certainly related to an anti virus or firewall on your side.

Do you have an anti virus with a web scanner or something similar running on your machine or are you behind a firewall?
