### ISSUE TITLE
Word by word segment info for Surah Audio.

### ISSUE THREAD

**Issue by DLkhazan** [islamic-network/alquran.cloud#35]
Can we have word by word breakdown segments of Surah Audios?
Example: https://api.quran.com/api/v4/chapter_recitations/1?segments=true&chapter=1

In Al-Quran api there is a wide range of reciters, it would be really helpful if you can provide the segments.

**Comment by meezaan** [comment]
This will likely only be possible for only those reciters where segment data is available. 

Every ayah has done this for some reciters - https://everyayah.com/data/timings_files/ - and perhaps that is the data used by the quran.com api. But this is only by ayah.

Creating this data is a mammoth task that will need community effort. There are some tools available on https://everyayah.com/data/tools/, but will require some investigation.
