### ISSUE TITLE
Alslamo alaikom my brother

### ISSUE THREAD

**Issue by Iam-Muslim** [islamic-network/alquran.cloud#40]
Al slamo alaikom my brothher 
This is a good work may Allah bless you <3

i need the Quran Text you used here 
maybe you have it in xml or json or excel or doc

**Comment by meezaan** [comment]
> Al slamo alaikom my brothher This is a good work may Allah bless you <3
> 
> i need the Quran Text you used here maybe you have it in xml or json or excel or doc

Alaykum Salaam. Please see https://alquran.cloud/api. Everything is accessible as JSON.
