### ISSUE TITLE
Url text is wrong but Url is correct

### ISSUE THREAD

**Issue by sanabel-al-firdaws** [islamic-network/alquran.cloud#42]
GET [Ayah - Get an Ayah of the Quran](https://alquran.cloud/api#collapseFive)

{{edition}} is an edition identifier. Example: en.asad for Muhammad Asad's english translation

[http://api.alquran.cloud/v1/ayah/262](http://api.alquran.cloud/v1/ayah/262/en.asad) - (Text) Returns Muhammad Asad's translation Ayat Al Kursi
> the link text is wrong here ^
[http://api.alquran.cloud/v1/ayah/2:255](http://api.alquran.cloud/v1/ayah/2:255/en.asad) - (Text) Returns Muhammad Asad's translation Ayat Al Kursi
http://api.alquran.cloud/v1/ayah/262/ar.alafasy - (Audio) Returns Mishary Alafasy's recitation of the Ayat Al Kursi
http://api.alquran.cloud/v1/ayah/262 - (Text) Returns the Arabic text of Ayat Al Kursi

**Comment by meezaan** [comment]
Fixed. Thank you.
