### ISSUE TITLE
gibberish characters in some surah name

### ISSUE THREAD

**Issue by mdahamshi** [islamic-network/alquran.cloud#43]
Hey
In some arabic surah name, I get weird characters:
![Screenshot from 2024-04-16 17-47-50](https://github.com/islamic-network/alquran.cloud/assets/24778772/9bcf140d-ea6d-482c-aa80-0d8fb47251aa)
How can I fix this ?

**Comment by meezaan** [comment]
This is purely a display problem. You need to use the right combination of font and edition. See https://alquran.cloud/arabic-font-edition-tester.
