### ISSUE TITLE
Data issue in quran-wordbyword

### ISSUE THREAD

**Issue by vipafattal** [islamic-network/alquran.cloud#9]
Peace up you, 
I've noticed an issue in API data in "quran-wordbyword" edition.
As you know in the Arabic words in the Quran we have a special character for ALEF which is (**ٰ**) we call it mini ALEF like "الرَّحْمٰنِ", "ذَٰلِكَ", "أُولَٰئِكَ".
Now the issue is mini ALEF in "quran-wordbyword" mustn't be ALEF with HAMZA instead just normal ALEF like this one "ا" but not this one "أ"
 Examples:
"وَ**ٲ**حِدَةٍ" must be "وَ**ا**حِدَةٍ"                       _(surah name: An-Nisaa, from aya number:1)_
"أَمْوَ**ٲ**لِكُمْ‌ۚ" must be "أَمْوَ**ا**لِكُمْ‌ۚ"                  _(surah name: An-Nisaa, from aya number:2)_

**The original text:** 
يَـٰٓأَيُّهَا|O|67|75|985$ٱلنَّاسُ|mankind!|78|94|112$ٱتَّقُواْ|Fear|64|80|2492$رَبَّكُمُ|your Lord|82|98|190$ٱلَّذِى|the One Who|107|123|138$خَلَقَكُم|created you|100|116|191$مِّن|from|50|66|53$نَّفْسٍ|a soul|62|70|2507$**وَٲحِدَةٍ**|single|78|93|3658$وَخَلَقَ|and created|100|129|3659$مِنْهَا|from it|63|92|246$زَوْجَهَا|its mate|87|116|3660$وَبَثَّ|and dispersed|111|140|1427$مِنْهُمَا|from both of them|140|155|966$رِجَالاً كَثِيرًا|many men|138|150|3661$وَنِسَآءً‌ۚ|and women.|100|125|3662$وَٱتَّقُواْ|And fear|78|103|467$ٱللَّهَ|Allah|53|78|184$ٱلَّذِى|(through) Whom|128|153|138$تَسَآءَلُونَ|you ask|103|116|3663$بِهِۦ|[with it]|74|83|204$وَٱلْأَرْحَامَ‌ۚ|and the wombs.|126|144|3664$إِنَّ|Indeed,|70|88|58$ٱللَّهَ|Allah|53|71|184$كَانَ|is|57|75|913$عَلَيْكُمْ|over you|78|96|416$رَقِيبًا|Ever-Watchful.|120|129|3665$

**The original text:** 
وَءَاتُواْ|And give|83|96|440$ٱلْيَتَـٰمَىٰٓ|(to) the orphans|130|156|1925$**أَمْوَٲلَهُمْ‌ۖ**|their wealth,|104|130|2360$وَلَا|and (do) not|104|130|25$تَتَبَدَّلُواْ|exchange|83|109|3666$ٱلْخَبِيثَ|the bad|90|103|2417$بِٱلطَّيِّبِ‌ۖ|with the good,|117|124|3667$وَلَا|and (do) not|104|118|25$تَأْكُلُوٓاْ|consume|78|92|3268$**أَمْوَٲلَهُمْ**|their wealth|99|114|2360$إِلَىٰٓ|with|53|68|118$**أَمْوَٲلِكُمْ‌ۚ**|your wealth.|103|118|3587$إِنَّهُۥ|Indeed, it|84|91|396$كَانَ|is|57|180|913$حُوبًا|a sin|66|311|3668$كَبِيرًا|great.|72|194|2548$

Thanks for your efforts.

**Comment by vipafattal** [comment]
> Peace up you,
> I've noticed an issue in API data in "quran-wordbyword" edition.
> As you know in the Arabic words in the Quran we have a special character for ALEF which is (**ٰ**) we call it mini ALEF like "الرَّحْمٰنِ", "ذَٰلِكَ", "أُولَٰئِكَ".
> Now the issue is mini ALEF in "quran-wordbyword" mustn't be ALEF with HAMZA instead just normal ALEF like this one "ا" but not this one "أ"
> Examples:
> "وَ**ٲ**حِدَةٍ" must be "وَ**ا**حِدَةٍ" _(surah name: An-Nisaa, from aya number:1)_
> "أَمْوَ**ٲ**لِكُمْ‌ۚ" must be "أَمْوَ**ا**لِكُمْ‌ۚ" _(surah name: An-Nisaa, from aya number:2)_
> 
> **The original text:**
> يَـٰٓأَيُّهَا|O|67|75|985$ٱلنَّاسُ|mankind!|78|94|112$ٱتَّقُواْ|Fear|64|80|2492$رَبَّكُمُ|your Lord|82|98|190$ٱلَّذِى|the One Who|107|123|138$خَلَقَكُم|created you|100|116|191$مِّن|from|50|66|53$نَّفْسٍ|a soul|62|70|2507$**وَٲحِدَةٍ**|single|78|93|3658$وَخَلَقَ|and created|100|129|3659$مِنْهَا|from it|63|92|246$زَوْجَهَا|its mate|87|116|3660$وَبَثَّ|and dispersed|111|140|1427$مِنْهُمَا|from both of them|140|155|966$رِجَالاً كَثِيرًا|many men|138|150|3661$وَنِسَآءً‌ۚ|and women.|100|125|3662$وَٱتَّقُواْ|And fear|78|103|467$ٱللَّهَ|Allah|53|78|184$ٱلَّذِى|(through) Whom|128|153|138$تَسَآءَلُونَ|you ask|103|116|3663$بِهِۦ|[with it]|74|83|204$وَٱلْأَرْحَامَ‌ۚ|and the wombs.|126|144|3664$إِنَّ|Indeed,|70|88|58$ٱللَّهَ|Allah|53|71|184$كَانَ|is|57|75|913$عَلَيْكُمْ|over you|78|96|416$رَقِيبًا|Ever-Watchful.|120|129|3665$
> 
> **The original text:**
> وَءَاتُواْ|And give|83|96|440$ٱلْيَتَـٰمَىٰٓ|(to) the orphans|130|156|1925$**أَمْوَٲلَهُمْ‌ۖ**|their wealth,|104|130|2360$وَلَا|and (do) not|104|130|25$تَتَبَدَّلُواْ|exchange|83|109|3666$ٱلْخَبِيثَ|the bad|90|103|2417$بِٱلطَّيِّبِ‌ۖ|with the good,|117|124|3667$وَلَا|and (do) not|104|118|25$تَأْكُلُوٓاْ|consume|78|92|3268$**أَمْوَٲلَهُمْ**|their wealth|99|114|2360$إِلَىٰٓ|with|53|68|118$**أَمْوَٲلِكُمْ‌ۚ**|your wealth.|103|118|3587$إِنَّهُۥ|Indeed, it|84|91|396$كَانَ|is|57|180|913$حُوبًا|a sin|66|311|3668$كَبِيرًا|great.|72|194|2548$
> 
> Thanks for your efforts.

@meezaan I thanks

**Comment by meezaan** [comment]
Alaykum Salaam @vipafattal and thank you for raising this.

This indeed seems to be incorrect - a hamzat-al-qatri should NOT be there.

Is this the only instance where you have seen this? I can change it, but if the same exists for other surahs and ayahs it probably needs to be raised with tanzil.net.

GlobalQuran.com has the same problem - see https://globalquran.com/en.ahmedali+quran-wordbyword/4:1 for instance.

Can you please confirm if you have spotted this inconsistency elsewhere or we can just mark this down to a typo and fix just this?

Shukran.

**Comment by vipafattal** [comment]
I can confirm that I've encountered this issue in many different places Quran word by word

سَمَـٰوَٲتٍ‌ۚ must be سَمَٰوَٰتٍۢ         (aya number:29 page:5 surah name: Al-Baqare)  

**The original text:**
هُوَ|He|48|60|298$ٱلَّذِى|(is) the One Who|134|158|138$خَلَقَ|created|71|95|299$لَكُم|for you|67|91|207$مَّا|what|53|77|262$فِى ٱلْأَرْضِ|(is) in the earth,|130|154|286$جَمِيعًا|all.|78|90|300$ثُمَّ|Moreover|81|89|293$ٱسْتَوَىٰٓ|He turned|86|103|301$إِلَى|to|53|70|118$ٱلسَّمَآءِ|the heaven|95|112|157$فَسَوَّٮٰهُنَّ|and fashioned them|150|167|302$سَبْعَ|seven|59|76|303$سَمَـٰوَٲتٍ‌ۚ|heavens.|101|109|304$وَهُوَ|And He|67|123|305$بِكُلِّ|of every|75|187|306$شَىْءٍ|thing|69|181|186$عَلِيمٌ|(is) All-Knowing.|128|184|307$1

وَٱلصَّلَوٲةِ‌ۚmust be ٱلصَّلَوٰةَ       (aya number:48 page:7 surah name: Al-Baqare)  

**The original text:**
وَٱسْتَعِينُواْ|And seek help|116|129|454$بِٱلصَّبْرِ|through patience|133|158|455$وَٱلصَّلَوٲةِ‌ۚ|and the prayer;|124|149|456$وَإِنَّهَا|and indeed, it|111|136|457$لَكَبِيرَةٌ|(is) surely difficult|140|153|458$إِلَّا|except|65|168|86$عَلَى|on|63|270|52$ٱلْخَـٰشِعِينَ|the humble ones,|134|237|459$


Thanks very much indeed, @meezaan.

**Comment by meezaan** [comment]
Shukran @vipafattal 

Please give me a couple of days to think about what to do - whether we need to take this version offline until it is fixed or at least put a note on the website. 

Any thoughts?

**Comment by vipafattal** [comment]
You know this is the Quran and it's extremely sensitive. but at the same time, I think there are dozens of apps using it and am one of them.
On the meantime, I'm just applying some conditions and actually it works very well with some exceptions and I'm happy with that.

Shukran Jazeelan @meezaan

**Comment by meezaan** [comment]
@vipafattal So this particular version is mirrored from Global Quran. I cannot actually find it on tanzil.net.

Can you please share what conditions you are applying and I can add them server side, because if we can't actually fix this in the next 3-5 days I will have to temporarily block this version until we can, because as you have said, it is a sensitive issue - not to mention that this actually changes the meaning in some places.

Shukran!

**Comment by meezaan** [comment]
Also @vipafattal do you use okhttp to make the calls? This particular edition has very low traffic. If that is the case, until we can fix it, God willing, I can simply block it at the firewall and let your requests in so the incorrect text does not spread, for lack of a better word.

Can you please email support [at] islamic.network and I will let you know how we can simply whitelist your connections in the meantime. Shukran.

**Comment by vipafattal** [comment]
Sorry for the late answer,
I'm using Retrofit which depends on OkHttp.
About the conditions, I'm using two editions quran-uthmani and quran-wordbyword, user can highlight some text in the app (this text is based on quran-uthmani) and then making a two copy of them.
In the first copy if the highlighted words if they contain ( ' ) I will replace it with ( أ ) 
In the second copy if the highlighted words if they contain ( ' ) I will replace it with ( ا ) 

with these and the original highlighted words, I am checking if there is any match with quran-wordbyword. 

Again Thanks very much.

**Comment by meezaan** [comment]
OK, I'll run some tests over the coming days to see if this fixes the overarching problem, insha Allah.

In the meantime, quran-wordbyword will no long return you results. Are you making the call server side of client side? If you are making it server side, please share your IP address by emailing support[at]islamic.network and I will whitelist it.

If not please, email there any way and we can agree on a new way to authenticate and whitelist your calls before the blacklist for quran-wordbyword fires.
